# Generated by Django 3.1.1 on 2020-10-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('attraction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('imageUrls', models.URLField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('imageUrls', models.URLField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('long_description', models.TextField()),
                ('short_description', models.TextField()),
                ('imageUrls', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DestinationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('comment_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.destination')),
            ],
        ),
        migrations.CreateModel(
            name='AttractionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('comment_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.attraction')),
            ],
        ),
        migrations.AddField(
            model_name='attraction',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.destination'),
        ),
    ]
