# Generated by Django 3.1.1 on 2020-11-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('attraction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
                ('StateCode', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('Recommendation_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('long_description', models.TextField()),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationComment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('comment_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.destination')),
            ],
        ),
        migrations.CreateModel(
            name='AttractionComment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('comment_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.attraction')),
            ],
        ),
        migrations.AddField(
            model_name='attraction',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.destination'),
        ),
    ]
