# Generated by Django 3.1.1 on 2020-11-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attraction_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='Recommendation_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
