# Generated by Django 3.1.1 on 2020-11-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201111_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
