# Generated by Django 3.1.1 on 2020-11-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201111_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='click_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='click_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
