# Generated by Django 3.1.1 on 2020-11-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201111_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='Recommendation_id',
            new_name='recommendation_id',
        ),
    ]
