# Generated by Django 3.1.1 on 2020-11-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201111_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='StateCode',
            new_name='stateCode',
        ),
        migrations.AddField(
            model_name='attraction',
            name='state',
            field=models.CharField(default='placeholder', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='stateCode',
            field=models.CharField(default='ph', max_length=10),
            preserve_default=False,
        ),
    ]
