# Generated by Django 3.0.1 on 2020-11-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201112_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='ABookmark', to='main.User'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='userLike',
            field=models.ManyToManyField(blank=True, default=None, related_name='ALike', to='main.User'),
        ),
        migrations.AddField(
            model_name='destination',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='DBookmark', to='main.User'),
        ),
        migrations.AddField(
            model_name='destination',
            name='userLike',
            field=models.ManyToManyField(blank=True, default=None, related_name='Dlike', to='main.User'),
        ),
    ]
