# Generated by Django 2.2.5 on 2020-11-15 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20201114_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='attraction',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='ABookmark', to='main.NormalUser'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='userLike',
            field=models.ManyToManyField(blank=True, default=None, related_name='ALike', to='main.NormalUser'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='DBookmark', to='main.NormalUser'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='userLike',
            field=models.ManyToManyField(blank=True, default=None, related_name='Dlike', to='main.NormalUser'),
        ),
    ]
