# Generated by Django 3.1.1 on 2020-11-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201115_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='state',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='stateCode',
        ),
        migrations.AddField(
            model_name='attraction',
            name='destination',
            field=models.ForeignKey(default='Sydney-NSW', on_delete=django.db.models.deletion.CASCADE, to='main.destination'),
            preserve_default=False,
        ),
    ]
