# Generated by Django 3.1.1 on 2020-11-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201115_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='city',
        ),
    ]
