# Generated by Django 2.2.5 on 2020-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201115_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='ABookmark', to='main.NormalUser'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='userLike',
            field=models.ManyToManyField(blank=True, default=None, related_name='ALike', to='main.NormalUser'),
        ),
        migrations.AddField(
            model_name='destination',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='DBookmark', to='main.NormalUser'),
        ),
        migrations.AddField(
            model_name='destination',
            name='userLike',
            field=models.ManyToManyField(blank=True, default=None, related_name='Dlike', to='main.NormalUser'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
