# Generated by Django 3.1.1 on 2020-11-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_attraction_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='destination',
            new_name='city',
        ),
    ]
