# Generated by Django 3.0.1 on 2020-11-16 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20201115_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='userDisLike',
            field=models.ManyToManyField(blank=True, default=None, related_name='ADislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destination',
            name='userDisLike',
            field=models.ManyToManyField(blank=True, default=None, related_name='DDislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
