# Generated by Django 3.0.1 on 2020-11-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201116_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='userDisLike',
            new_name='userDislike',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='userDisLike',
            new_name='userDislike',
        ),
    ]
