# Generated by Django 3.1.1 on 2020-11-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201116_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='/assets/image.png', upload_to=''),
        ),
    ]
