# Generated by Django 3.0.1 on 2020-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201116_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='attraction_bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='Abook', to='main.Attraction'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='destination_bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='Dbook', to='main.Destination'),
        ),
    ]
