# Generated by Django 3.0.1 on 2020-11-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201117_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='bookmark',
        ),
    ]
