# Generated by Django 3.1.1 on 2020-11-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201117_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='image.png', upload_to=''),
        ),
    ]
