# Generated by Django 3.1.1 on 2020-11-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201117_0621'),
        ('main', '0015_auto_20201117_0418'),
    ]

    operations = [
    ]
